# Generated by Django 5.2.14 on 2026-05-20 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0002_user_mfa_secret_authevent_usersession'),
        ('companies', '0001_initial'),
        ('devices', '0001_initial'),
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=16)),
                ('type', models.CharField(choices=[('device_down', 'Device Down'), ('cable_cut', 'Cable Cut'), ('signal_degraded', 'Signal Degraded'), ('threshold_breach', 'Threshold Breach'), ('maintenance_due', 'Maintenance Due'), ('capacity_warning', 'Capacity Warning'), ('security', 'Security'), ('system', 'System')], db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('affected_customers', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='accounts.user')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='accounts.user')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='topology.fiberroute')),
            ],
            options={
                'db_table': 'noc_alerts',
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['company', 'status', '-timestamp'], name='noc_alerts_company_4b29d8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['company', 'severity', '-timestamp'], name='noc_alerts_company_b26ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['company', 'type', '-timestamp'], name='noc_alerts_company_ebf388_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['company', 'device', '-timestamp'], name='noc_alerts_company_9a2e57_idx'),
        ),
    ]
