# Generated by Django 5.2.14 on 2026-05-20 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('parameter', models.CharField(choices=[('rx_power', 'RX Power'), ('tx_power', 'TX Power'), ('temperature', 'Temperature'), ('packet_loss', 'Packet Loss'), ('latency', 'Latency'), ('cpu_usage', 'CPU Usage'), ('memory_usage', 'Memory Usage'), ('optical_loss', 'Optical Loss')], db_index=True, max_length=32)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='companies.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
            ],
            options={
                'db_table': 'noc_telemetry_readings',
            },
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['company', 'device', 'parameter', '-timestamp'], name='noc_telemet_company_d6e0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['company', 'parameter', '-timestamp'], name='noc_telemet_company_94ac3e_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['company', '-timestamp'], name='noc_telemet_company_0ee0c9_idx'),
        ),
    ]
