# Generated by Django 5.2.14 on 2026-05-20 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models

try:
    from django.contrib.gis.db.models.fields import LineStringField as FiberGeometryField
except Exception:  # GeoDjango libs (GDAL/GEOS) may be unavailable in dev environments
    FiberGeometryField = None


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('route_type', models.CharField(choices=[('feeder', 'Feeder'), ('distribution', 'Distribution'), ('drop', 'Drop'), ('backbone', 'Backbone')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('degraded', 'Degraded'), ('down', 'Down')], default='planned', max_length=32)),
                ('geometry', FiberGeometryField(geography=True, srid=4326) if FiberGeometryField else models.JSONField(blank=True, default=dict)),
                ('length_meters', models.FloatField(default=0.0)),
                ('attenuation_db_km', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('capacity_gbps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_routes', to='companies.company')),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_out', to='devices.device')),
                ('to_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_in', to='devices.device')),
            ],
            options={
                'db_table': 'noc_fiber_routes',
            },
        ),
        migrations.AddConstraint(
            model_name='fiberroute',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_fiber_route_company_name'),
        ),
        migrations.AddIndex(
            model_name='fiberroute',
            index=models.Index(fields=['company', 'route_type', 'status'], name='noc_fiber_r_company_492eca_idx'),
        ),
        migrations.AddIndex(
            model_name='fiberroute',
            index=models.Index(fields=['company', 'from_device'], name='noc_fiber_r_company_8e5aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='fiberroute',
            index=models.Index(fields=['company', 'to_device'], name='noc_fiber_r_company_9f9186_idx'),
        ),
    ]
