# Generated by Django 5.2.14 on 2026-05-20 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(db_index=True, max_length=64)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='companies.company')),
            ],
            options={
                'db_table': 'noc_workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=64)),
                ('event_name', models.CharField(db_index=True, max_length=128)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='companies.company')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflow')),
            ],
            options={
                'db_table': 'noc_workflow_runs',
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_workflow_company_name'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['company', 'trigger_type', 'is_active'], name='noc_workflo_company_9fc95e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['company', '-updated_at'], name='noc_workflo_company_29e159_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['company', 'status', '-started_at'], name='noc_workfl_company_fbf0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['company', 'event_name', '-started_at'], name='noc_workfl_company_7d76f5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['workflow', '-started_at'], name='noc_workfl_workflo_1fceab_idx'),
        ),
    ]

