# Generated by Django 5.2.14 on 2026-05-20 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models

try:
    from django.contrib.gis.db.models.fields import PointField as DeviceLocationField
except Exception:  # GeoDjango libs (GDAL/GEOS) may be unavailable in dev environments
    DeviceLocationField = None


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('OLT', 'OLT'), ('ONT', 'ONT'), ('Splitter', 'Splitter'), ('Router', 'Router'), ('Switch', 'Switch'), ('JJB', 'JJB'), ('Coupler', 'Coupler')], max_length=32)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded'), ('maintenance', 'Maintenance')], default='offline', max_length=32)),
                ('location', DeviceLocationField(geography=True, srid=4326) if DeviceLocationField else models.JSONField(blank=True, default=dict)),
                ('region', models.CharField(db_index=True, max_length=120)),
                ('uptime', models.FloatField(default=0.0)),
                ('tx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('rx_power', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='devices.device')),
            ],
            options={
                'db_table': 'noc_devices',
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_device_company_name'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'type', 'status'], name='noc_devices_company_55fec6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'region'], name='noc_devices_company_b0f0df_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'parent'], name='noc_devices_company_5f32c4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', '-last_seen'], name='noc_devices_company_f2b9fd_idx'),
        ),
    ]
